"""Generate _rtfm/ output directory with Obsidian-native navigation files."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from rtfm.core.library import Library


def _vault_path_to_wikilink(rel_path: str) -> str:
    """Convert a relative file path to an Obsidian wikilink.

    ``"notes/My Note.md"`` → ``"[[notes/My Note]]"``
    """
    p = Path(rel_path)
    if p.suffix.lower() == ".md":
        return f"[[{p.with_suffix('')}]]"
    return f"[[{rel_path}]]"


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _frontmatter(tags: list[str], extra: dict | None = None) -> str:
    """Generate YAML frontmatter block."""
    lines = ["---"]
    tag_str = ", ".join(tags)
    lines.append(f"tags: [{tag_str}]")
    lines.append(f"generated_at: \"{_now_iso()}\"")
    lines.append("cssclasses: [rtfm-generated]")
    if extra:
        for k, v in extra.items():
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines)


def _generate_index(library: "Library", vault_root: Path, config: dict) -> str:
    """Generate _rtfm/index.md — main navigation hub."""
    stats = library.get_stats()
    corpora = library.list_corpora()

    fm = _frontmatter(
        ["rtfm", "rtfm/index"],
        {"total_documents": stats.get("books", 0), "total_chunks": stats.get("chunks", 0)},
    )

    lines = [fm, ""]
    lines.append("# RTFM — Vault Index")
    lines.append("")
    lines.append("> [!info] Vault Stats")
    lines.append(f"> 📄 {stats.get('books', 0)} documents · "
                 f"{stats.get('chunks', 0)} chunks · "
                 f"{len(corpora)} corpora")
    lines.append("")
    lines.append("> [!warning] Auto-generated")
    lines.append("> This file is generated by RTFM. Do not edit manually.")
    lines.append("> Regenerate with `rtfm vault --regenerate`.")
    lines.append("")

    # Corpora list
    lines.append("## Corpora")
    lines.append("")
    for c in corpora:
        name = c["corpus"]
        count = c.get("book_count", 0)
        lines.append(f"- [[_rtfm/corpus/{name}|{name}]] — {count} documents")

    lines.append("")

    # Top connected documents
    in_degree = library.get_in_degree()
    if in_degree:
        # Get book info for top entries
        conn = library._get_conn()
        top_ids = sorted(in_degree.items(), key=lambda x: -x[1])[:10]
        lines.append("## Most Connected Documents")
        lines.append("")
        for book_id, degree in top_ids:
            row = conn.execute(
                "SELECT filename, title FROM books WHERE id = ?", (book_id,)
            ).fetchone()
            if row and row["filename"]:
                wl = _vault_path_to_wikilink(row["filename"])
                lines.append(f"- {wl} — {degree} backlinks")
        lines.append("")

    # Search instructions
    lines.append("## Search")
    lines.append("")
    lines.append("In Claude Code, use RTFM tools:")
    lines.append("```")
    lines.append('rtfm_search("your query")')
    lines.append('rtfm_expand("source-slug")')
    lines.append("```")
    lines.append("")

    # Recommended plugins
    lines.append("## Recommended Obsidian Plugins")
    lines.append("")
    lines.append("- **Dataview** — Query RTFM metadata: "
                 "`TABLE generated_at, total_documents FROM #rtfm`")
    lines.append("- **Graph View** (core) — `_rtfm/` pages connect to all indexed files")
    lines.append("")

    return "\n".join(lines)


def _generate_corpus_page(library: "Library", vault_root: Path, corpus: str) -> str:
    """Generate _rtfm/corpus/<name>.md — per-corpus index."""
    conn = library._get_conn()
    books = conn.execute(
        """SELECT id, slug, title, filename, corpus, chunk_count, total_chars
           FROM books WHERE corpus = ? ORDER BY filename""",
        (corpus,)
    ).fetchall()

    fm = _frontmatter(
        ["rtfm", "rtfm/corpus"],
        {"corpus": f'"{corpus}"', "total_documents": len(books)},
    )

    lines = [fm, ""]
    lines.append(f"# Corpus: {corpus}")
    lines.append("")
    lines.append("> [!info] Stats")
    total_chars = sum(b["total_chars"] or 0 for b in books)
    total_chunks = sum(b["chunk_count"] or 0 for b in books)
    lines.append(f"> 📄 {len(books)} documents · {total_chunks} chunks · "
                 f"{total_chars:,} chars")
    lines.append("")

    # File listing
    lines.append("## Documents")
    lines.append("")
    for b in books:
        filename = b["filename"]
        if filename:
            wl = _vault_path_to_wikilink(filename)
            chunks = b["chunk_count"] or 0
            lines.append(f"- {wl} ({chunks} chunks)")
    lines.append("")

    # Top connected in this corpus
    in_degree = library.get_in_degree()
    if in_degree:
        corpus_book_ids = {b["id"] for b in books}
        corpus_degrees = {bid: d for bid, d in in_degree.items() if bid in corpus_book_ids}
        if corpus_degrees:
            top = sorted(corpus_degrees.items(), key=lambda x: -x[1])[:5]
            lines.append("## Most Connected")
            lines.append("")
            for book_id, degree in top:
                row = conn.execute(
                    "SELECT filename FROM books WHERE id = ?", (book_id,)
                ).fetchone()
                if row and row["filename"]:
                    wl = _vault_path_to_wikilink(row["filename"])
                    lines.append(f"- {wl} — {degree} backlinks")
            lines.append("")

    return "\n".join(lines)


def _generate_graph_page(library: "Library", vault_root: Path) -> str:
    """Generate _rtfm/graph.md — knowledge graph analysis."""
    graph_stats = library.get_graph_stats()
    in_degree = library.get_in_degree()

    fm = _frontmatter(
        ["rtfm", "rtfm/graph"],
        {"total_edges": graph_stats.get("total_edges", 0)},
    )

    lines = [fm, ""]
    lines.append("# Knowledge Graph")
    lines.append("")
    lines.append("> [!info] Graph Stats")
    lines.append(f"> 🔗 {graph_stats.get('total_edges', 0)} edges · "
                 f"{graph_stats.get('books_with_edges', 0)} connected documents")
    lines.append("")

    conn = library._get_conn()

    # Hubs (top 20 by in-degree)
    if in_degree:
        top = sorted(in_degree.items(), key=lambda x: -x[1])[:20]
        lines.append("## Hub Documents")
        lines.append("")
        for book_id, degree in top:
            row = conn.execute(
                "SELECT filename, title FROM books WHERE id = ?", (book_id,)
            ).fetchone()
            if row and row["filename"]:
                wl = _vault_path_to_wikilink(row["filename"])
                lines.append(f"- {wl} — {degree} backlinks")
        lines.append("")

    # Orphans (no edges)
    all_books = conn.execute("SELECT id, filename FROM books").fetchall()
    books_with_edges = set()
    edges = conn.execute(
        "SELECT source_book_id, target_book_id FROM edges"
    ).fetchall()
    for e in edges:
        books_with_edges.add(e["source_book_id"])
        books_with_edges.add(e["target_book_id"])

    orphans = [b for b in all_books if b["id"] not in books_with_edges and b["filename"]]
    if orphans:
        lines.append("## Orphan Documents")
        lines.append("")
        lines.append(f"> [!warning] {len(orphans)} documents with no links")
        lines.append("")
        for b in orphans[:30]:
            wl = _vault_path_to_wikilink(b["filename"])
            lines.append(f"- {wl}")
        if len(orphans) > 30:
            lines.append(f"- ... and {len(orphans) - 30} more")
        lines.append("")

    # Edge types breakdown
    relation_types = graph_stats.get("relation_types", {})
    if relation_types:
        lines.append("## Edge Types")
        lines.append("")
        for rtype, count in sorted(relation_types.items(), key=lambda x: -x[1]):
            lines.append(f"- **{rtype}**: {count}")
        lines.append("")

    # Mermaid diagram (top 15 connections)
    if edges:
        lines.append("## Top Connections")
        lines.append("")
        lines.append("```mermaid")
        lines.append("graph LR")

        # Get top edges by combining with in-degree
        edge_rows = conn.execute("""
            SELECT e.source_book_id, e.target_book_id,
                   s.filename as source_file, t.filename as target_file
            FROM edges e
            JOIN books s ON e.source_book_id = s.id
            JOIN books t ON e.target_book_id = t.id
            LIMIT 15
        """).fetchall()

        seen_nodes = set()
        for e in edge_rows:
            src = Path(e["source_file"]).stem if e["source_file"] else "?"
            tgt = Path(e["target_file"]).stem if e["target_file"] else "?"
            # Sanitize for Mermaid
            src_id = src.replace(" ", "_").replace("-", "_")[:20]
            tgt_id = tgt.replace(" ", "_").replace("-", "_")[:20]
            if src_id not in seen_nodes:
                lines.append(f"    {src_id}[\"{src}\"]")
                seen_nodes.add(src_id)
            if tgt_id not in seen_nodes:
                lines.append(f"    {tgt_id}[\"{tgt}\"]")
                seen_nodes.add(tgt_id)
            lines.append(f"    {src_id} --> {tgt_id}")

        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def _generate_recent_page(library: "Library", vault_root: Path) -> str:
    """Generate _rtfm/recent.md — recently modified files."""
    fm = _frontmatter(["rtfm", "rtfm/recent"])

    conn = library._get_conn()
    rows = conn.execute("""
        SELECT filepath, indexed_at, corpus
        FROM indexed_files
        ORDER BY indexed_at DESC
        LIMIT 20
    """).fetchall()

    lines = [fm, ""]
    lines.append("# Recently Modified")
    lines.append("")
    lines.append(f"> Last updated: {_now_iso()}")
    lines.append("")

    for row in rows:
        wl = _vault_path_to_wikilink(row["filepath"])
        ts = row["indexed_at"][:16] if row["indexed_at"] else "?"
        corpus = row["corpus"] or ""
        lines.append(f"- {wl} — `{corpus}` — {ts}")
    lines.append("")

    return "\n".join(lines)


def generate_vault_output(
    library: "Library",
    vault_root: Path,
    config: dict,
) -> dict:
    """Generate all _rtfm/ output files.

    Args:
        library: Open RTFM Library instance.
        vault_root: Path to the vault root.
        config: RTFM config dict.

    Returns:
        Summary dict with files written.
    """
    vault_root = Path(vault_root)
    rtfm_dir = vault_root / "_rtfm"
    corpus_dir = rtfm_dir / "corpus"
    corpus_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []

    # index.md
    content = _generate_index(library, vault_root, config)
    (rtfm_dir / "index.md").write_text(content, encoding="utf-8")
    written.append("_rtfm/index.md")

    # graph.md
    content = _generate_graph_page(library, vault_root)
    (rtfm_dir / "graph.md").write_text(content, encoding="utf-8")
    written.append("_rtfm/graph.md")

    # recent.md
    content = _generate_recent_page(library, vault_root)
    (rtfm_dir / "recent.md").write_text(content, encoding="utf-8")
    written.append("_rtfm/recent.md")

    # Per-corpus pages
    corpora = library.list_corpora()
    for c in corpora:
        name = c["corpus"]
        content = _generate_corpus_page(library, vault_root, name)
        (corpus_dir / f"{name}.md").write_text(content, encoding="utf-8")
        written.append(f"_rtfm/corpus/{name}.md")

    return {"files_written": written, "count": len(written)}


def update_recent_page(library: "Library", vault_root: Path) -> None:
    """Lightweight update: only regenerate _rtfm/recent.md.

    Called after each sync when vault_type == "obsidian".
    """
    vault_root = Path(vault_root)
    rtfm_dir = vault_root / "_rtfm"
    if not rtfm_dir.is_dir():
        return

    content = _generate_recent_page(library, vault_root)
    (rtfm_dir / "recent.md").write_text(content, encoding="utf-8")
